# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out parent repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env:
            GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
            repository: 'billypchan/carthageDummyD'
            path: carthageDummyD
      - name: update D cartfile
        run: |
          sed -i '' 's/\(github "billypchan\/carthageDummyE" ~> \)\(.*\)$/\12.0/g' carthageDummyD/Cartfile
          cat carthageDummyD/Cartfile
          ls -l

      - name: commit to D
        run: |
          cd carthageDummyD
          git branch chore/bump
          git checkout chore/bump
          git add .
          git commit -m"bump E"
          git log
          
      - name: push
        run: |
          cd carthageDummyD
          git config --local user.name "Github Action"
          git config --global user.email "billypchan@gmail.com"
          git push https://$USERNAME:$GITHUB_TOKEN@github.com/billypchan/carthageDummyD.git
        env:
            GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
            USERNAME: billypchan
